### ISSUE TITLE
How to use this class

### ISSUE THREAD

**Issue by timors** [sebtalasi/SAP_MAIL#1]
Hi.I want to learn a class like this.

**Comment by sebtalasi** [comment]
Hi ! :-) 

I'll commit a new version today. 
I'll try to publish a detailed "how to" guide next week. ;-) 

Here are some indications if you want to use it before that :
1. To get it on your sap system, you can use AbapGit. 
The class will be in a dedicated package on your system. 

2. Then, to use it, simply create a class wich inheritate from ZCL_MAIL. 

3. Here it should be quite straitforward :
build* methods are to be redifined (they are abstracted).
To fill the mail body, you can use the read_text method.
It reads an SO10 text and use an importing table to replace specific parts of the text (Ex : &myVar&) 

Have fun !

**Comment by timors** [comment]
Thanks !
I have a try.
